LOCAL_DIR := $(GET_LOCAL_DIR)

MODULE_SRCS += \
	$(LOCAL_DIR)/FloatMathPlugin.c \
	$(LOCAL_DIR)/acos.c \
	$(LOCAL_DIR)/acosh.c \
	$(LOCAL_DIR)/asin.c \
	$(LOCAL_DIR)/asinh.c \
	$(LOCAL_DIR)/atan.c \
	$(LOCAL_DIR)/atan2.c \
	$(LOCAL_DIR)/atanh.c \
	$(LOCAL_DIR)/copysign.c \
	$(LOCAL_DIR)/cos.c \
	$(LOCAL_DIR)/cosh.c \
	$(LOCAL_DIR)/exp.c \
	$(LOCAL_DIR)/expm1.c \
	$(LOCAL_DIR)/finite.c \
	$(LOCAL_DIR)/fmod.c \
	$(LOCAL_DIR)/hypot.c \
	$(LOCAL_DIR)/isnan.c \
	$(LOCAL_DIR)/k_cos.c \
	$(LOCAL_DIR)/k_rem_pio2.c \
	$(LOCAL_DIR)/k_sin.c \
	$(LOCAL_DIR)/k_tan.c \
	$(LOCAL_DIR)/ldexp.c \
	$(LOCAL_DIR)/log.c \
	$(LOCAL_DIR)/log10.c \
	$(LOCAL_DIR)/log1p.c \
	$(LOCAL_DIR)/modf.c \
	$(LOCAL_DIR)/pow.c \
	$(LOCAL_DIR)/rem_pio2.c \
	$(LOCAL_DIR)/rint.c \
	$(LOCAL_DIR)/scalb.c \
	$(LOCAL_DIR)/scalbn.c \
	$(LOCAL_DIR)/sin.c \
	$(LOCAL_DIR)/sinh.c \
	$(LOCAL_DIR)/sqrt.c \
	$(LOCAL_DIR)/tan.c \
	$(LOCAL_DIR)/tanh.c \
